### ISSUE TITLE
Change the Schedule Overlay to be Collapsable

### ISSUE THREAD

**Issue by jeremywight** [dacohenii/trolley-tracker-web#4]
@Linktheoriginal @dacohenii I recommend we update the styling of the schedule display and make it a bit more user-friendly when you arrive on the page and the trolley is not running, by making it collapsable.

**Comment by Linktheoriginal** [comment]
Isn't it already collapsible with the close button at the bottom?  What should it look like instead?

I just checked the yeahthattrolley site - can you direct the iframe to /trolley instead of at the testing url?

**Comment by dacohenii** [comment]
done.

--
David A. Cohen II
(864) 986-0007
